import fs from "node:fs";
import path from "node:path";

import BetterSqlite3 from "better-sqlite3";
import { describe, expect, it } from "vitest";

import { generatePostgresSchema } from "../scripts/generate-postgres-schema.js";
import { initializeDatabaseSchema } from "../src/db/database.js";
import { POSTGRES_MIGRATION_CONTRACT } from "../src/db/postgres-migration-contract.js";
import {
  sha256PostgresMigrationContract,
  type PostgresMigrationConversion,
} from "../src/db/postgres-migration-schema.js";

const sqliteSchema = fs.readFileSync(
  path.resolve(process.cwd(), "src/db/schema.sql"),
  "utf8",
);
const databaseModule = fs.readFileSync(
  path.resolve(process.cwd(), "src/db/database.ts"),
  "utf8",
);
const checkedInPostgresSchema = fs.readFileSync(
  path.resolve(process.cwd(), "src/db/postgres-schema.sql"),
  "utf8",
);
const supabaseRuntimeMigrations = fs.readdirSync(
  path.resolve(process.cwd(), "supabase/migrations"),
).filter((fileName) => fileName.endsWith("_create_pintpath_postgres_runtime.sql"));
const logicalBackupForwardMigrations = fs.readdirSync(
  path.resolve(process.cwd(), "supabase/migrations"),
).filter((fileName) => fileName.endsWith("_add_pintpath_logical_backup_role.sql"));
const verifierAuthorityForwardMigrations = fs.readdirSync(
  path.resolve(process.cwd(), "supabase/migrations"),
).filter((fileName) => fileName.endsWith("_add_postgres_migration_verifier_authority.sql"));

const expectedTargetTypeByConversion = {
  binary: "bytea",
  boolean: "boolean",
  "calendar-month": "text",
  decimal: "numeric",
  float64: "double precision",
  integer: "bigint",
  "json-array": "jsonb",
  "json-object": "jsonb",
  "local-time": "time without time zone",
  text: "text",
  "utc-instant": "timestamptz",
} as const satisfies Record<PostgresMigrationConversion, string>;

const expectedSourceTypeCounts = {
  bigint: 27,
  boolean: 28,
  bytea: 3,
  "double precision": 6,
  integer: 0,
  jsonb: 29,
  numeric: 14,
  text: 434,
  "time without time zone": 4,
  timestamptz: 172,
} as const;

const metadataTables = [
  "pintpath_app.schema_metadata",
  "pintpath_ops.migration_chunks",
  "pintpath_ops.migration_runs",
  "pintpath_ops.migration_verifier_authority",
] as const;

const expectedSchemaMetadata = new Map<string, string | RegExp>([
  ["import_state", "empty"],
  ["live_schema_sha256", ""],
  ["migration_candidate_sha", ""],
  ["migration_contract_sha256", /^[a-f0-9]{64}$/],
  ["migration_manifest_sha256", ""],
  ["migration_plan_sha256", ""],
  ["migration_run_sha256", ""],
  ["schema_version", "1"],
  ["source_schema_fingerprint", ""],
  ["source_schema_sha256", /^[a-f0-9]{64}$/],
  ["source_schema_version", "0"],
  ["source_snapshot_sha256", ""],
  ["target_ddl_sha256", ""],
]);

interface PostgresTableDefinition {
  schema: "pintpath_app" | "pintpath_ops";
  name: string;
  qualifiedName: string;
}

function generateSchema(): string {
  return generatePostgresSchema({ sqliteSchema, databaseModule });
}

function withInitializedDatabase<Result>(
  work: (database: BetterSqlite3.Database) => Result,
): Result {
  const database = new BetterSqlite3(":memory:");
  try {
    initializeDatabaseSchema(database);
    return work(database);
  } finally {
    database.close();
  }
}

function postgresTables(sql: string): PostgresTableDefinition[] {
  return Array.from(
    sql.matchAll(/^CREATE TABLE\s+((?:[a-z0-9_]+\.)?[a-z0-9_]+)\s*\(/gim),
    (match): PostgresTableDefinition => {
      const [first, second] = match[1]!.split(".");
      const schema = second ? first as PostgresTableDefinition["schema"] : "pintpath_app";
      const name = second ?? first!;
      return { schema, name, qualifiedName: `${schema}.${name}` };
    },
  );
}

function postgresIndexNames(sql: string): string[] {
  return Array.from(
    sql.matchAll(/^CREATE\s+(?:UNIQUE\s+)?INDEX\s+([a-z0-9_]+)\b/gim),
    (match) => match[1]!,
  );
}

function postgresSourceTableBody(sql: string, tableName: string): string {
  const match = new RegExp(`^CREATE TABLE ${tableName} \\(\\n([\\s\\S]*?)^\\);$`, "m").exec(sql);
  if (!match) throw new Error(`Unable to find generated source table ${tableName}.`);
  return match[1]!;
}

function generatedColumnType(sql: string, tableName: string, columnName: string): string {
  const body = postgresSourceTableBody(sql, tableName);
  const match = new RegExp(
    `^  ${columnName} (bigint|boolean|bytea|double precision|integer|jsonb|numeric|text|time without time zone|timestamptz)\\b`,
    "m",
  ).exec(body);
  if (!match) throw new Error(`Unable to find generated column ${tableName}.${columnName}.`);
  return match[1]!;
}

describe("Postgres schema generation", () => {
  it("is deterministic and keeps the checked-in generated schema current", () => {
    const first = generateSchema();
    const second = generateSchema();

    expect(first).toBe(second);
    expect(first).toBe(checkedInPostgresSchema);
    expect(first).toMatch(
      /^-- Generated by scripts\/generate-postgres-schema\.ts\. Do not edit by hand\./,
    );
    expect(first).toMatch(/-- Canonical SQLite schema SHA-256: [a-f0-9]{64}/);
    const contractChecksum = sha256PostgresMigrationContract(POSTGRES_MIGRATION_CONTRACT);
    expect(first).toContain(`-- Reviewed migration contract SHA-256: ${contractChecksum}`);
    expect(first).toContain(`('migration_contract_sha256', '${contractChecksum}')`);

    expect(supabaseRuntimeMigrations).toHaveLength(1);
    const checkedInSupabaseMigration = fs.readFileSync(
      path.resolve(process.cwd(), "supabase/migrations", supabaseRuntimeMigrations[0]!),
      "utf8",
    );
    expect(checkedInSupabaseMigration).toBe(first);
  });

  it("prepopulates exactly the metadata rows that the update-only importer requires", () => {
    const generated = generateSchema();
    const insert = /INSERT INTO schema_metadata \(key, value\) VALUES\n([\s\S]*?);/.exec(generated)?.[1];
    expect(insert).toBeDefined();
    const entries = Array.from(
      insert!.matchAll(/^  \('([^']+)', '([^']*)'\)(?:,)?$/gm),
      (match) => [match[1]!, match[2]!] as const,
    );
    const actual = new Map(entries);

    expect(insert).toBe(entries
      .map(([key, value], index) => `  ('${key}', '${value}')${index < entries.length - 1 ? "," : ""}`)
      .join("\n"));
    expect(entries).toHaveLength(expectedSchemaMetadata.size);
    expect(actual.size).toBe(entries.length);
    expect([...actual.keys()].sort()).toEqual([...expectedSchemaMetadata.keys()].sort());
    for (const [key, expectedValue] of expectedSchemaMetadata) {
      const actualValue = actual.get(key);
      if (expectedValue instanceof RegExp) {
        expect(actualValue, key).toMatch(expectedValue);
      } else {
        expect(actualValue, key).toBe(expectedValue);
      }
    }
  });

  it("maps all 717 reviewed source columns to their exact native Postgres types", () => {
    const generated = generateSchema();
    const actualCounts: Record<string, number> = {
      bigint: 0,
      boolean: 0,
      bytea: 0,
      "double precision": 0,
      integer: 0,
      jsonb: 0,
      numeric: 0,
      text: 0,
      "time without time zone": 0,
      timestamptz: 0,
    };
    let sourceColumnCount = 0;

    for (const table of POSTGRES_MIGRATION_CONTRACT.tables) {
      for (const [columnName, , conversion] of table.columns) {
        const actualType = generatedColumnType(generated, table.name, columnName);
        expect(
          actualType,
          `${table.name}.${columnName} must follow the reviewed ${conversion} conversion`,
        ).toBe(expectedTargetTypeByConversion[conversion]);
        actualCounts[actualType] = (actualCounts[actualType] ?? 0) + 1;
        sourceColumnCount += 1;
      }
    }

    expect(sourceColumnCount).toBe(717);
    expect(actualCounts).toEqual(expectedSourceTypeCounts);
  });

  it("uses native boolean, JSON, instant, local-time, and decimal constraints", () => {
    const generated = generateSchema();

    for (const table of POSTGRES_MIGRATION_CONTRACT.tables) {
      const tableBody = postgresSourceTableBody(generated, table.name);
      for (const [columnName, , conversion] of table.columns) {
        const declaration = tableBody.match(new RegExp(`^  ${columnName} [^\\n]+`, "m"))?.[0];
        expect(declaration, `${table.name}.${columnName} must have a declaration`).toBeDefined();
        if (conversion === "boolean") {
          expect(declaration).not.toMatch(/\bDEFAULT\s+[01]\b/i);
        }
        if (conversion === "json-array" || conversion === "json-object") {
          expect(declaration).toContain(
            `CHECK (jsonb_typeof(${columnName}) = '${conversion === "json-array" ? "array" : "object"}')`,
          );
        }
        if (conversion === "calendar-month") {
          expect(declaration).toContain(
            `CHECK (${columnName} ~ '^[0-9]{4}-(0[1-9]|1[0-2])$')`,
          );
        }
      }
    }

    expect(generated).toContain("secret_purge_checkpoint_pending IN (false, true)");
    expect(generated).not.toContain("secret_purge_checkpoint_pending IN (0, 1)");
    expect(postgresSourceTableBody(generated, "venue_claim_requests"))
      .toContain("status IN ('approved', 'rejected') AND reviewed_at IS NOT NULL");
    expect(postgresSourceTableBody(generated, "venue_claim_requests"))
      .not.toContain("julianday(reviewed_at)");
    expect(postgresSourceTableBody(generated, "venue_manager_assignments"))
      .toContain("access_level = 'counter_staff' AND expires_at IS NOT NULL");
    expect(postgresSourceTableBody(generated, "venue_manager_assignments"))
      .not.toContain("julianday(expires_at)");
  });

  it("converts both static JSON defaults without disturbing quoted backslash literals", () => {
    const adversarialSqlLiteral = String.raw`'C:\imports\O''Brien.json'`;
    const schemaWithAdjacentLiteral = sqliteSchema.replace(
      "  extracted_beers_json TEXT NOT NULL DEFAULT '[]',",
      `  extracted_beers_json TEXT NOT NULL DEFAULT '[]' CHECK (`
      + `extracted_beers_json <> ${adversarialSqlLiteral}),`,
    );
    expect(schemaWithAdjacentLiteral).not.toBe(sqliteSchema);

    const generated = generatePostgresSchema({
      sqliteSchema: schemaWithAdjacentLiteral,
      databaseModule,
    });

    expect(postgresSourceTableBody(generated, "admin_ingestion_queue")).toContain(
      `extracted_beers_json jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (`
      + `extracted_beers_json <> ${adversarialSqlLiteral}) `
      + "CHECK (jsonb_typeof(extracted_beers_json) = 'array')",
    );
    expect(postgresSourceTableBody(generated, "discount_redemptions")).toContain(
      "metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb "
      + "CHECK (jsonb_typeof(metadata_json) = 'object')",
    );
  });

  it("contains all 56 source tables exactly once plus only the four control tables", () => {
    withInitializedDatabase((database) => {
      const sourceTables = database
        .prepare(
          `SELECT name
           FROM sqlite_master
           WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
           ORDER BY name`,
        )
        .all()
        .map((row) => (row as { name: string }).name);
      const generatedTables = postgresTables(generateSchema());
      const applicationSourceTables = generatedTables
        .filter((table) => table.schema === "pintpath_app" && sourceTables.includes(table.name))
        .map((table) => table.name);

      expect(sourceTables).toHaveLength(56);
      expect(new Set(generatedTables.map(({ qualifiedName }) => qualifiedName)).size)
        .toBe(generatedTables.length);
      expect(generatedTables).toHaveLength(60);
      expect(applicationSourceTables.sort()).toEqual(sourceTables);
      expect(generatedTables
        .filter((table) => !sourceTables.includes(table.name))
        .map(({ qualifiedName }) => qualifiedName)
        .sort())
        .toEqual([...metadataTables]);
    });
  });

  it("keeps the additive logical-backup upgrade bound to the exact generated inventory", () => {
    expect(logicalBackupForwardMigrations).toHaveLength(1);
    const migration = fs.readFileSync(
      path.resolve(
        process.cwd(),
        "supabase/migrations",
        logicalBackupForwardMigrations[0]!,
      ),
      "utf8",
    );
    const qualifiedTables = postgresTables(generateSchema())
      .map((table) => table.qualifiedName)
      .filter((name) => name !== "pintpath_ops.migration_verifier_authority")
      .sort();
    const expectedInventory = Array.from(
      migration.matchAll(/^    '(pintpath_(?:app|ops)\.[a-z0-9_]+)'[,]?$/gm),
      (match) => match[1]!,
    );

    expect(qualifiedTables).toHaveLength(59);
    expect(expectedInventory).toEqual(qualifiedTables);
    expect(migration).toContain("Expected exactly 59 reviewed application/control tables.");
    expect(migration).toContain(
      "backup_role_name := 'pintpath_logical_backup_d' || current_database_oid_text;",
    );
    expect(migration).toContain(
      "'create role %I nologin nosuperuser nocreatedb nocreaterole noinherit noreplication nobypassrls'",
    );
    expect(migration).toContain("migration_state := 'absent'");
    expect(migration).toContain("migration_state := 'restored-policy-only'");
    expect(migration).toContain("migration_state := 'exact-candidate'");
    expect(migration).toContain(
      "perform pg_catalog.pg_advisory_xact_lock(-1516610544307388182);",
    );
    expect(migration).toContain("reserved_login_role_count <> 0");
    expect(migration).toContain("where membership.member = role.oid");
    expect(migration).toContain("where membership.roleid = role.oid");
    expect(migration).toContain("policy.polroles = array[0]::oid[]");
    expect(migration).toContain("private_policy_count = 177");
    expect(migration).toContain("private_policy_count = 236");
    expect(migration).toContain("exact_base_policy_count = 177");
    expect(migration).toContain("private_policy_count <> 236");
    expect(migration).toContain("exact_base_policy_count <> 177");
    expect(migration).toContain("where role.rolname = current_user");
    expect(migration).toContain("elsif executor_is_superuser then");
    expect(migration).toContain("if migration_state = 'absent' then");
    expect(migration).toContain("if role_exists and migration_state <> 'exact' then");
    expect(migration).toContain("did not preserve an exact policy-only state");
    expect(migration).toContain("a policy directly names the scoped role");
    expect(migration).toContain("dependency.deptype = 'a'");
    expect(migration).toContain(") = 61");
    expect(migration).toContain(
      "current_user = (''pintpath_logical_backup_d'' || (select database.oid::text",
    );
    expect(migration).toContain("relation.relkind = 'S'");
    expect(migration).toContain(
      "grant select on all sequences in schema pintpath_app, pintpath_ops",
    );
    expect(migration).not.toMatch(
      /grant\s+(?:insert|update|delete|truncate|references|trigger|usage)\s+on\s+(?:table|all tables|sequence|all sequences)/i,
    );
    expect(migration).not.toMatch(/grant\s+execute\s+on\s+function/i);
    expect(migration).not.toMatch(/alter\s+role\s+pintpath_logical_backup/i);
    expect(migration).not.toMatch(/to\s+pintpath_logical_backup(?:\s|;|$)/i);
  });

  it("keeps one post-activation additive verifier-authority migration for existing databases", () => {
    expect(verifierAuthorityForwardMigrations).toHaveLength(1);
    const fileName = verifierAuthorityForwardMigrations[0]!;
    expect(fileName.localeCompare(
      "20260813000000_activate_reviewed_price_promotion_kernel.sql",
    )).toBeGreaterThan(0);
    const migration = fs.readFileSync(
      path.resolve(process.cwd(), "supabase/migrations", fileName),
      "utf8",
    );

    expect(migration).toContain("pg_advisory_xact_lock(721426590137322906)");
    expect(migration).toContain("create role pintpath_migration_verifier_authority");
    expect(migration).toContain("create table pintpath_ops.migration_verifier_authority");
    expect(migration.match(/create policy migration_verifier_authority_/g))
      .toHaveLength(4);
    expect(migration).toContain(
      "grant select on pintpath_ops.migration_verifier_authority\n      to pintpath_migrator",
    );
    expect(migration).toContain(
      "grant select, insert, update on pintpath_ops.migration_verifier_authority",
    );
    expect(migration).not.toMatch(/grant[^;]*delete/i);
    expect(migration).toContain(
      "exists (select 1 from pintpath_ops.migration_verifier_authority)",
    );
  });

  it("orders every source table after all of its non-self foreign-key dependencies", () => {
    withInitializedDatabase((database) => {
      const generatedTables = postgresTables(generateSchema());
      const generatedOrder = generatedTables.map(({ name }) => name);
      const generatedPosition = new Map(
        generatedOrder.map((tableName, position) => [tableName, position]),
      );
      const sourceTables = database
        .prepare(
          `SELECT name
           FROM sqlite_master
           WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
           ORDER BY name`,
        )
        .all() as Array<{ name: string }>;

      for (const { name: tableName } of sourceTables) {
        const tablePosition = generatedPosition.get(tableName);
        expect(tablePosition, `${tableName} must exist in the generated schema`).toBeTypeOf("number");
        const dependencies = database
          .prepare(`PRAGMA foreign_key_list(${tableName})`)
          .all() as Array<{ table: string }>;
        for (const { table: dependency } of dependencies) {
          if (dependency === tableName) continue;
          const dependencyPosition = generatedPosition.get(dependency);
          expect(
            dependencyPosition,
            `${tableName} references missing table ${dependency}`,
          ).toBeTypeOf("number");
          expect(
            dependencyPosition!,
            `${dependency} must be created before ${tableName}`,
          ).toBeLessThan(tablePosition!);
        }
      }

      const qualifiedPosition = new Map(
        generatedTables.map(({ qualifiedName }, position) => [qualifiedName, position]),
      );
      expect(qualifiedPosition.get("pintpath_ops.migration_runs"))
        .toBeLessThan(qualifiedPosition.get("pintpath_ops.migration_chunks")!);
    });
  });

  it("retains all 76 foreign keys, all 74 source key constraints, and every source check", () => {
    withInitializedDatabase((database) => {
      const sourceTables = database
        .prepare(
          `SELECT name, sql
           FROM sqlite_master
           WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
           ORDER BY name`,
        )
        .all() as Array<{ name: string; sql: string }>;
      const generated = generateSchema();
      const generatedBodies = sourceTables
        .map(({ name }) => postgresSourceTableBody(generated, name))
        .join("\n");
      const sourceForeignKeys = sourceTables.reduce(
        (total, { name }) => total + (
          database.pragma(`foreign_key_list(${name})`) as unknown[]
        ).length,
        0,
      );
      const sourceAutomaticIndexes = sourceTables.reduce(
        (total, { name }) => total + (
          database.pragma(`index_list(${name})`) as Array<{ origin: string }>
        ).filter(({ origin }) => origin !== "c").length,
        0,
      );
      const sourceChecks = sourceTables.reduce(
        (total, { sql }) => total + (sql.match(/\bCHECK\s*\(/g) ?? []).length,
        0,
      );
      const reviewedShapeChecks = POSTGRES_MIGRATION_CONTRACT.tables.reduce(
        (total, table) => total + table.columns.filter(([, , conversion]) => (
          conversion === "json-array"
          || conversion === "json-object"
          || conversion === "calendar-month"
        )).length,
        0,
      );

      expect(sourceForeignKeys).toBe(76);
      expect((generatedBodies.match(/\bREFERENCES\b/g) ?? [])).toHaveLength(sourceForeignKeys);
      expect(sourceAutomaticIndexes).toBe(74);
      expect(
        (generatedBodies.match(/\bPRIMARY KEY\b/g) ?? []).length
        + (generatedBodies.match(/\bUNIQUE\b/g) ?? []).length,
      ).toBe(sourceAutomaticIndexes);
      expect(sourceChecks).toBe(15);
      expect((generatedBodies.match(/\bCHECK\s*\(/g) ?? [])).toHaveLength(
        sourceChecks + reviewedShapeChecks,
      );
    });
  });

  it("preserves the complete runtime explicit-index set", () => {
    withInitializedDatabase((database) => {
      const sourceIndexes = database
        .prepare(
          `SELECT name, tbl_name AS tableName, sql
           FROM sqlite_master
           WHERE type = 'index' AND sql IS NOT NULL
           ORDER BY name`,
        )
        .all() as Array<{ name: string; tableName: string; sql: string }>;
      const sourceIndexNames = sourceIndexes.map(({ name }) => name);
      const allGeneratedIndexNames = postgresIndexNames(generateSchema()).sort();
      const generatedSourceIndexNames = allGeneratedIndexNames
        .filter((name) => name !== "migration_runs_source_target_unique");
      const venueRequestSourceSubmissionIndexes = sourceIndexes.filter((index) => {
        if (index.tableName !== "venue_requests") return false;
        const columns = database
          .prepare(`PRAGMA index_info(${index.name})`)
          .all() as Array<{ seqno: number; name: string }>;
        return columns
          .sort((left, right) => left.seqno - right.seqno)[0]?.name === "source_submission_id";
      });

      // The prior source contract had 162 explicit indexes. The missing
      // venue_requests(source_submission_id) FK access path, the three
      // deterministic mission keyset access paths, the venue-request keyset
      // path, and the two venue-partner keyset paths raise the reviewed
      // contract to 172 without weakening exact set parity. The three admin
      // analytics indexes add deterministic/covering production read paths,
      // and the six privacy-retention indexes raise the reviewed total to 178.
      // Five venue-data read indexes cover deterministic duplicate detection
      // and venue-scoped published-beer lookups, raising the total to 183. Two
      // venue-manager detail indexes remove full scans and raise it to 185.
      expect(sourceIndexes).toHaveLength(
        venueRequestSourceSubmissionIndexes.length > 0 ? 185 : 184,
      );
      expect(generatedSourceIndexNames).toEqual(sourceIndexNames);
      expect(allGeneratedIndexNames.filter((name) => !sourceIndexNames.includes(name)))
        .toEqual(["migration_runs_source_target_unique"]);
      expect(new Set(allGeneratedIndexNames).size).toBe(allGeneratedIndexNames.length);

      for (const { name } of venueRequestSourceSubmissionIndexes) {
        expect(generatedSourceIndexNames).toContain(name);
      }

      const generated = generateSchema();
      expect(generated).toContain(`CREATE INDEX idx_missions_admin_active_score
  ON missions ((points * multiplier) DESC, updated_at DESC, id ASC)
  INCLUDE (venue_name)
  WHERE active;`);
      expect(generated).toContain(`CREATE INDEX idx_missions_venue_updated_id
  ON missions (venue_id, updated_at DESC, id ASC)
  INCLUDE (venue_name);`);
      expect(generated).toContain(`CREATE INDEX idx_auth_sessions_retention_revoked
  ON auth_sessions (revoked_at, token_hash COLLATE "C")
  WHERE revoked_at IS NOT NULL;`);
      expect(generated).toContain(`CREATE INDEX idx_auth_sessions_retention_expired
  ON auth_sessions (expires_at, token_hash COLLATE "C");`);
      expect(generated).toContain(`CREATE INDEX idx_revoked_provider_sessions_retention
  ON revoked_provider_sessions (
    revoked_at,
    user_id COLLATE "C",
    provider_session_id_hash COLLATE "C"
  )
  WHERE reason IN ('password_reset_completed', 'all_app_sessions_revoked');`);
      expect(generated).toContain(`CREATE INDEX idx_submissions_reviewed_location_retention
  ON submissions (reviewed_at, id COLLATE "C")`);
      expect(generated).toContain(`CREATE INDEX idx_submissions_venue_created_id
  ON submissions (venue_id, created_at DESC, id COLLATE "C");`);
      expect(generated).toContain(`CREATE INDEX idx_migration_quarantined_records_retention
  ON migration_quarantined_records (quarantined_at, id COLLATE "C")
  WHERE payload_json <> '{"redactedAfterRetention":true}'::jsonb;`);
      expect(generated).toContain(`CREATE INDEX idx_account_deletion_notification_events_retention
  ON account_deletion_notification_events (received_at, event_id COLLATE "C")
  INCLUDE (request_id);`);
      expect(generated).toContain(`CREATE INDEX idx_contribution_ledger_created_points
  ON contribution_ledger (created_at)
  INCLUDE (points);`);
      expect(generated).toContain(`CREATE INDEX idx_venue_profiles_duplicate_name
  ON venue_profiles (
    lower(btrim(name)),
    lower(btrim(COALESCE(suburb, ''))),
    venue_id COLLATE "C"
  )
  INCLUDE (name, suburb)
  WHERE active;`);
      expect(generated).toContain(`CREATE INDEX idx_venue_location_cache_duplicate_name
  ON venue_location_cache (
    lower(btrim(venue_name)),
    lower(btrim(COALESCE(suburb, ''))),
    venue_id COLLATE "C"
  )
  INCLUDE (venue_name, suburb);`);
      expect(generated).toContain(`CREATE INDEX idx_venue_price_records_duplicate_name
  ON venue_price_records (
    lower(btrim(venue_name)),
    lower(btrim(COALESCE(suburb, ''))),
    venue_id COLLATE "C",
    id COLLATE "C"
  )
  INCLUDE (venue_name, suburb);`);
      expect(generated).toContain(`CREATE INDEX idx_venue_price_records_venue_normalized_beer
  ON venue_price_records (venue_id, normalized_beer_id)
  WHERE normalized_beer_id IS NOT NULL;`);
      expect(generated).toContain(`CREATE INDEX idx_venue_price_records_venue_beer_name
  ON venue_price_records (venue_id, lower(btrim(beer_name)));`);
      expect(generated).toContain(`CREATE INDEX idx_wrong_price_reports_venue_created_id
  ON wrong_price_reports (venue_id, created_at DESC, id COLLATE "C");`);
    });
  });

  it("keeps every generated table behind the private runtime and migrator RLS boundaries", () => {
    const generated = generateSchema();
    const generatedTables = postgresTables(generated);
    const sourceApplicationTables = generatedTables.filter(
      (table) => table.schema === "pintpath_app" && table.name !== "schema_metadata",
    );

    expect(generated).toContain("CREATE SCHEMA pintpath_app;");
    expect(generated).toContain("CREATE SCHEMA pintpath_ops;");
    expect(generated).toContain("REVOKE ALL ON SCHEMA pintpath_app FROM PUBLIC;");
    expect(generated).toContain("REVOKE ALL ON SCHEMA pintpath_ops FROM PUBLIC;");
    expect(generated).toContain("GRANT USAGE ON SCHEMA pintpath_app TO pintpath_runtime;");
    expect(generated).not.toContain("GRANT USAGE ON SCHEMA pintpath_ops TO pintpath_runtime;");
    expect(generated).toContain("GRANT USAGE ON SCHEMA pintpath_app TO pintpath_migrator;");
    expect(generated).toContain("GRANT USAGE ON SCHEMA pintpath_ops TO pintpath_migrator;");
    expect(generated).toContain(
      "'GRANT USAGE ON SCHEMA pintpath_app, pintpath_ops TO %I'",
    );
    expect(generated).toContain("SET LOCAL search_path = pintpath_app, pg_catalog;");
    expect(generated).toMatch(
      /CREATE ROLE pintpath_runtime\s+NOLOGIN\s+NOSUPERUSER\s+NOCREATEDB\s+NOCREATEROLE\s+INHERIT\s+NOREPLICATION\s+NOBYPASSRLS;/,
    );
    expect(generated).toMatch(
      /CREATE ROLE pintpath_migrator\s+NOLOGIN\s+NOSUPERUSER\s+NOCREATEDB\s+NOCREATEROLE\s+INHERIT\s+NOREPLICATION\s+NOBYPASSRLS;/,
    );
    expect(generated).toContain(
      "'CREATE ROLE %I NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'",
    );
    expect(generated).toContain(
      "backup_role_name := 'pintpath_logical_backup_d' || database_oid_text;",
    );
    expect(generated).toContain("database_oid_text !~ '^[1-9][0-9]{0,9}$'");
    expect(generated).toContain("backup_role_name || '\\_v%'");
    expect(generated).toContain("WHERE role.rolname = current_user;");
    expect(generated).toContain("IF NOT role_exists AND NOT executor_is_superuser THEN");
    expect(generated).toContain("RETURN;");
    expect(generated).toContain(
      "leave the portable policies inert instead of",
    );
    expect(generated).not.toMatch(
      /ALTER ROLE\s+pintpath_(?:runtime|migrator|logical_backup)\b/i,
    );
    expect(generated).toMatch(
      /FOREACH role_name IN ARRAY ARRAY\[\s*'pintpath_runtime',\s*'pintpath_migrator',\s*'pintpath_migration_verifier_authority'\s*\] LOOP/,
    );
    for (const unsafeAttributePredicate of [
      "roles.rolcanlogin",
      "roles.rolsuper",
      "roles.rolcreatedb",
      "roles.rolcreaterole",
      "NOT roles.rolinherit",
      "roles.rolreplication",
      "roles.rolbypassrls",
    ]) {
      expect(generated).toContain(unsafeAttributePredicate);
    }
    expect(generated).toContain("ERRCODE = '42501'");
    expect(generated).toContain(
      "Refusing Pint Path schema bootstrap because role %I has unsafe attributes.",
    );
    expect(generated).toContain(
      "Have a cluster administrator harden or recreate the role, then rerun this migration.",
    );
    expect(generated).toContain("WHERE membership.member = role.oid");
    expect(generated).toContain("WHERE membership.roleid = role.oid");
    expect(generated).toContain("dependency.deptype = 'a'");
    expect(generated).toContain(") <> 61 OR (");
    expect(generated).toContain("private_policy_count <> 240");
    expect(generated).toContain("exact_base_policy_count <> 181");
    expect(generated).toContain("exact_backup_policy_count <> 59");
    expect(generated).toContain("non-canonical private policy inventory");
    expect(generated).not.toMatch(/SECURITY\s+DEFINER/i);

    for (const { name: tableName } of sourceApplicationTables) {
      expect(generated).toContain(`ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;`);
      expect(generated).toContain(`ALTER TABLE ${tableName} FORCE ROW LEVEL SECURITY;`);
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_runtime_all ON ${tableName}\n  FOR ALL TO pintpath_runtime USING (true) WITH CHECK (true);`,
      );
      expect(generated).toContain(
        `GRANT SELECT, INSERT, UPDATE, DELETE ON ${tableName} TO pintpath_runtime;`,
      );
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_migrator_select ON ${tableName}\n  FOR SELECT TO pintpath_migrator USING (true);`,
      );
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_migrator_insert ON ${tableName}\n  FOR INSERT TO pintpath_migrator WITH CHECK (true);`,
      );
      expect(generated).toContain(`GRANT SELECT, INSERT ON ${tableName} TO pintpath_migrator;`);
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_logical_backup_select ON pintpath_app.${tableName}\n  AS PERMISSIVE\n  FOR SELECT TO PUBLIC\n  USING (CURRENT_USER = ('pintpath_logical_backup_d' || (SELECT database.oid::text`,
      );
      expect(generated).toContain(
        `('pintpath_app', '${tableName}')`,
      );
      expect(generated).not.toContain(
        `GRANT SELECT, INSERT, UPDATE ON ${tableName} TO pintpath_migrator;`,
      );
    }

    expect(generated).toContain("ALTER TABLE schema_metadata ENABLE ROW LEVEL SECURITY;");
    expect(generated).toContain("ALTER TABLE schema_metadata FORCE ROW LEVEL SECURITY;");
    expect(generated).toContain(
      "CREATE POLICY schema_metadata_runtime_read ON schema_metadata\n  FOR SELECT TO pintpath_runtime USING (true);",
    );
    expect(generated).toContain("GRANT SELECT ON schema_metadata TO pintpath_runtime;");
    expect(generated).toContain(
      "CREATE POLICY schema_metadata_migrator_select ON schema_metadata\n  FOR SELECT TO pintpath_migrator USING (true);",
    );
    expect(generated).toContain(
      "CREATE POLICY schema_metadata_migrator_update ON schema_metadata\n  FOR UPDATE TO pintpath_migrator USING (true) WITH CHECK (true);",
    );
    expect(generated).toContain("GRANT SELECT, UPDATE ON schema_metadata TO pintpath_migrator;");
    expect(generated).toContain(
      "CREATE POLICY schema_metadata_logical_backup_select ON pintpath_app.schema_metadata\n  AS PERMISSIVE\n  FOR SELECT TO PUBLIC",
    );
    expect(generated).toContain("('pintpath_app', 'schema_metadata')");
    expect(generated).not.toContain("CREATE POLICY schema_metadata_migrator_insert");
    expect(generated).not.toMatch(
      /GRANT\s+[^;]*\bINSERT\b[^;]*ON\s+(?:pintpath_app\.)?schema_metadata\s+TO\s+pintpath_migrator\b/i,
    );
    expect(generated).not.toContain(
      "GRANT SELECT, INSERT, UPDATE, DELETE ON schema_metadata TO pintpath_runtime;",
    );
    expect(generated).not.toMatch(
      /GRANT[\s\S]*?ON\s+pintpath_ops\.(?:migration_runs|migration_chunks)\s+TO\s+pintpath_runtime/i,
    );

    for (const tableName of ["migration_runs", "migration_chunks"]) {
      expect(generated).toContain(
        `ALTER TABLE pintpath_ops.${tableName} ENABLE ROW LEVEL SECURITY;`,
      );
      expect(generated).toContain(
        `ALTER TABLE pintpath_ops.${tableName} FORCE ROW LEVEL SECURITY;`,
      );
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_migrator_select ON pintpath_ops.${tableName}\n  FOR SELECT TO pintpath_migrator USING (true);`,
      );
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_migrator_insert ON pintpath_ops.${tableName}\n  FOR INSERT TO pintpath_migrator WITH CHECK (true);`,
      );
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_migrator_update ON pintpath_ops.${tableName}\n  FOR UPDATE TO pintpath_migrator USING (true) WITH CHECK (true);`,
      );
      expect(generated).toContain(
        `GRANT SELECT, INSERT, UPDATE ON pintpath_ops.${tableName} TO pintpath_migrator;`,
      );
      expect(generated).toContain(
        `CREATE POLICY ${tableName}_logical_backup_select ON pintpath_ops.${tableName}\n  AS PERMISSIVE\n  FOR SELECT TO PUBLIC`,
      );
      expect(generated).toContain(
        `('pintpath_ops', '${tableName}')`,
      );
    }
    expect(generated).not.toMatch(
      /GRANT\s+[^;]*(?:DELETE|TRUNCATE)[^;]*\s+TO\s+pintpath_migrator\b/i,
    );
    expect(generated).not.toMatch(
      /'GRANT\s+[^']*\b(?:INSERT|UPDATE|DELETE|TRUNCATE|REFERENCES|TRIGGER)\b[^']*\s+TO\s+%I'/i,
    );
    expect(generated).toContain(
      "'GRANT SELECT ON ALL SEQUENCES IN SCHEMA pintpath_app, pintpath_ops TO %I'",
    );
    expect(generated).not.toMatch(
      /'GRANT\s+(?:USAGE|UPDATE)[^']*ON(?:\s+ALL)?\s+SEQUENCES?[^']*TO\s+%I'/i,
    );
    expect(generated).not.toMatch(
      /'GRANT\s+EXECUTE\s+ON[^']*TO\s+%I'/i,
    );
    expect(generated.match(/FOR SELECT TO PUBLIC/g)).toHaveLength(59);
    expect(generated).not.toMatch(/FOR SELECT TO pintpath_logical_backup_d[0-9]+/i);

    const accessStatements = generated
      .split(";")
      .filter((statement) => /\b(?:GRANT|REVOKE|CREATE\s+POLICY)\b/i.test(statement));
    for (const statement of accessStatements) {
      expect(statement).not.toMatch(/\b(?:anon|authenticated)\b/i);
      if (/\bGRANT\b/i.test(statement)) {
        expect(statement).not.toMatch(/\bTO\s+PUBLIC\b/i);
      }
    }

    expect(generated).toContain(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA pintpath_app REVOKE ALL ON TABLES FROM PUBLIC;",
    );
    expect(generated).toContain(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA pintpath_app REVOKE ALL ON SEQUENCES FROM PUBLIC;",
    );
    expect(generated).toContain(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA pintpath_app REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;",
    );
    expect(generated).toContain(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA pintpath_ops REVOKE ALL ON TABLES FROM PUBLIC;",
    );
    expect(generated).toContain(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA pintpath_ops REVOKE ALL ON SEQUENCES FROM PUBLIC;",
    );
    expect(generated).toContain(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA pintpath_ops REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;",
    );
    expect(generated).toContain(
      "REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA pintpath_app FROM PUBLIC;",
    );
    expect(generated).toContain(
      "REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA pintpath_ops FROM PUBLIC;",
    );
  });
});
