export interface BeerCatalogItem {
  key: string;
  name: string;
  aliases: string[];
  brewery?: string;
  style?: string;
  abv?: number;
}

export const BEER_CATALOG: readonly BeerCatalogItem[] = [
  { key: "guinness", name: "Guinness", aliases: ["guinness", "guinness draught"], brewery: "Guinness", style: "Stout", abv: 4.2 },
  { key: "carlton_draft", name: "Carlton Draught", aliases: ["carlton draft", "carlton draught"], brewery: "Carlton & United Breweries", style: "Lager", abv: 4.6 },
  { key: "stone_and_wood_pacific_ale", name: "Stone & Wood Pacific Ale", aliases: ["stone and wood", "stone & wood", "stone wood", "pacific ale"], brewery: "Stone & Wood", style: "Pacific ale", abv: 4.4 },
  { key: "victoria_bitter", name: "Victoria Bitter", aliases: ["vb", "victoria bitter"], brewery: "Carlton & United Breweries", style: "Lager", abv: 4.9 },
  { key: "melbourne_bitter", name: "Melbourne Bitter", aliases: ["melbourne bitter"], brewery: "Carlton & United Breweries", style: "Lager", abv: 4.6 },
  { key: "reschs_draught", name: "Resch's Draught", aliases: ["reschs", "resch's", "reschs draught", "resch's draught"], brewery: "Carlton & United Breweries", style: "Lager", abv: 4.5 },
  { key: "great_northern_original", name: "Great Northern Original", aliases: ["great northern", "great northern original"], brewery: "Great Northern", style: "Lager", abv: 4.2 },
  { key: "great_northern_super_crisp", name: "Great Northern Super Crisp", aliases: ["super crisp", "great northern super crisp"], brewery: "Great Northern", style: "Lager", abv: 3.5 },
  { key: "pure_blonde", name: "Pure Blonde", aliases: ["pure blonde"], brewery: "Carlton & United Breweries", style: "Lager", abv: 4.2 },
  { key: "cascade_premium_light", name: "Cascade Premium Light", aliases: ["cascade light", "cascade premium light"], brewery: "Cascade", style: "Light lager", abv: 2.4 },
  { key: "crown_lager", name: "Crown Lager", aliases: ["crown", "crown lager"], brewery: "Carlton & United Breweries", style: "Lager", abv: 4.9 },
  { key: "fosters_lager", name: "Foster's Lager", aliases: ["fosters", "foster lager", "foster's"], brewery: "Foster's", style: "Lager", abv: 4.0 },
  { key: "tooheys_new", name: "Tooheys New", aliases: ["tooheys new"], brewery: "Tooheys", style: "Lager", abv: 4.6 },
  { key: "tooheys_old", name: "Tooheys Old", aliases: ["old", "tooheys old"], brewery: "Tooheys", style: "Dark ale", abv: 4.4 },
  { key: "xxxx_gold", name: "XXXX Gold", aliases: ["xxxx", "xxxx gold", "four x gold"], brewery: "XXXX", style: "Mid-strength lager", abv: 3.5 },
  { key: "coopers_pale_ale", name: "Coopers Pale Ale", aliases: ["coopers pale", "coopers pale ale"], brewery: "Coopers", style: "Pale ale", abv: 4.5 },
  { key: "coopers_sparkling_ale", name: "Coopers Sparkling Ale", aliases: ["coopers sparkling", "coopers sparkling ale"], brewery: "Coopers", style: "Sparkling ale", abv: 5.8 },
  { key: "coopers_mild_ale", name: "Coopers Mild Ale", aliases: ["coopers mild", "coopers mild ale"], brewery: "Coopers", style: "Mid-strength ale", abv: 3.5 },
  { key: "coopers_stout", name: "Coopers Best Extra Stout", aliases: ["coopers stout", "coopers best extra stout"], brewery: "Coopers", style: "Stout", abv: 6.3 },
  { key: "hahn_super_dry", name: "Hahn Super Dry", aliases: ["hahn", "hahn super dry"], brewery: "Hahn", style: "Lager", abv: 4.6 },
  { key: "hahn_super_dry_35", name: "Hahn Super Dry 3.5", aliases: ["hahn 3.5", "hahn super dry 3.5"], brewery: "Hahn", style: "Mid-strength lager", abv: 3.5 },
  { key: "james_boags_premium", name: "James Boag's Premium", aliases: ["boags", "boag's", "james boags", "james boag's premium"], brewery: "James Boag", style: "Lager", abv: 4.6 },
  { key: "james_squire_150_lashes", name: "James Squire 150 Lashes", aliases: ["150 lashes", "one fifty lashes", "james squire lashes"], brewery: "James Squire", style: "Pale ale", abv: 4.2 },
  { key: "james_squire_orchard_crush", name: "James Squire Orchard Crush", aliases: ["orchard crush", "james squire cider"], brewery: "James Squire", style: "Cider", abv: 4.8 },
  { key: "furphy_refreshing_ale", name: "Furphy Refreshing Ale", aliases: ["furphy", "furphy ale"], brewery: "Furphy", style: "Ale", abv: 4.4 },
  { key: "little_creatures_pale_ale", name: "Little Creatures Pale Ale", aliases: ["little creatures", "little creatures pale", "little creatures pale ale"], brewery: "Little Creatures", style: "Pale ale", abv: 5.2 },
  { key: "little_creatures_rogers", name: "Little Creatures Rogers", aliases: ["rogers", "little creatures rogers"], brewery: "Little Creatures", style: "Amber ale", abv: 3.8 },
  { key: "white_rabbit_dark_ale", name: "White Rabbit Dark Ale", aliases: ["white rabbit", "white rabbit dark"], brewery: "White Rabbit", style: "Dark ale", abv: 4.9 },
  { key: "white_rabbit_white_ale", name: "White Rabbit White Ale", aliases: ["white rabbit white", "white ale"], brewery: "White Rabbit", style: "Wheat beer", abv: 4.5 },
  { key: "balter_xpa", name: "Balter XPA", aliases: ["balter", "balter xpa"], brewery: "Balter", style: "XPA", abv: 5.0 },
  { key: "balter_cerveza", name: "Balter Cerveza", aliases: ["balter cerveza"], brewery: "Balter", style: "Lager", abv: 4.0 },
  { key: "balter_hazy_ipa", name: "Balter Hazy IPA", aliases: ["balter hazy", "balter hazy ipa"], brewery: "Balter", style: "Hazy IPA", abv: 6.0 },
  { key: "young_henrys_newtowner", name: "Young Henrys Newtowner", aliases: ["young henrys", "young henry's", "newtowner"], brewery: "Young Henrys", style: "Pale ale", abv: 4.8 },
  { key: "young_henrys_natural_lager", name: "Young Henrys Natural Lager", aliases: ["young henrys lager", "young henry's lager"], brewery: "Young Henrys", style: "Lager", abv: 4.2 },
  { key: "pirate_life_south_coast_pale", name: "Pirate Life South Coast Pale Ale", aliases: ["pirate life", "pirate life pale", "south coast pale"], brewery: "Pirate Life", style: "Pale ale", abv: 4.4 },
  { key: "pirate_life_ipa", name: "Pirate Life IPA", aliases: ["pirate life ipa"], brewery: "Pirate Life", style: "IPA", abv: 6.8 },
  { key: "mountain_goat_lager", name: "Mountain Goat Lager", aliases: ["goat lager", "mountain goat"], brewery: "Mountain Goat", style: "Lager", abv: 4.2 },
  { key: "mountain_goat_pale_ale", name: "Mountain Goat Pale Ale", aliases: ["goat pale", "mountain goat pale"], brewery: "Mountain Goat", style: "Pale ale", abv: 4.2 },
  { key: "moon_dog_old_mate", name: "Moon Dog Old Mate", aliases: ["old mate", "moon dog", "moondog"], brewery: "Moon Dog", style: "Pale ale", abv: 5.0 },
  { key: "moon_dog_lager", name: "Moon Dog Lager", aliases: ["moon dog lager", "moondog lager"], brewery: "Moon Dog", style: "Lager", abv: 4.5 },
  { key: "stomping_ground_gipps_st_pale", name: "Stomping Ground Gipps St Pale Ale", aliases: ["stomping ground", "gipps st", "gipps street pale"], brewery: "Stomping Ground", style: "Pale ale", abv: 5.2 },
  { key: "stomping_ground_laneway_lager", name: "Stomping Ground Laneway Lager", aliases: ["laneway lager", "stomping ground lager"], brewery: "Stomping Ground", style: "Lager", abv: 4.7 },
  { key: "bodriggy_speccy_juice", name: "Bodriggy Speccy Juice", aliases: ["speccy juice", "bodriggy"], brewery: "Bodriggy", style: "Session IPA", abv: 3.5 },
  { key: "bodriggy_fuzzy_dance_explosion", name: "Bodriggy Fuzzy Dance Explosion", aliases: ["fuzzy dance", "bodriggy fuzzy"], brewery: "Bodriggy", style: "Hazy IPA", abv: 6.3 },
  { key: "hop_nation_the_heart", name: "Hop Nation The Heart", aliases: ["the heart", "hop nation"], brewery: "Hop Nation", style: "Pale ale", abv: 4.6 },
  { key: "hop_nation_jedi_juice", name: "Hop Nation Jedi Juice", aliases: ["jedi juice", "hop nation jedi"], brewery: "Hop Nation", style: "NEIPA", abv: 7.1 },
  { key: "bonehead_sweet_pea", name: "Bonehead Sweet Pea", aliases: ["sweet pea", "bonehead"], brewery: "Bonehead Brewing", style: "Pale ale", abv: 4.8 },
  { key: "deeds_xpa", name: "Deeds XPA", aliases: ["deeds", "deeds xpa"], brewery: "Deeds Brewing", style: "XPA", abv: 4.2 },
  { key: "fixation_ipa", name: "Fixation IPA", aliases: ["fixation", "fixation ipa"], brewery: "Fixation", style: "IPA", abv: 6.4 },
  { key: "hawkers_pale_ale", name: "Hawkers Pale Ale", aliases: ["hawkers", "hawkers pale"], brewery: "Hawkers", style: "Pale ale", abv: 4.8 },
  { key: "hawkers_lager", name: "Hawkers Lager", aliases: ["hawkers lager"], brewery: "Hawkers", style: "Lager", abv: 4.2 },
  { key: "wolf_of_the_willows_xpa", name: "Wolf of the Willows XPA", aliases: ["wolf of the willows", "wolf xpa"], brewery: "Wolf of the Willows", style: "XPA", abv: 4.7 },
  { key: "two_bays_pale_ale", name: "Two Bays Pale Ale", aliases: ["two bays", "two bays pale"], brewery: "Two Bays", style: "Gluten free pale ale", abv: 4.5 },
  { key: "urban_alley_urban_ale", name: "Urban Alley Urban Ale", aliases: ["urban alley", "urban ale"], brewery: "Urban Alley", style: "Pale ale", abv: 4.5 },
  { key: "blackmans_reginald_ipa", name: "Blackman's Reginald IPA", aliases: ["blackmans", "blackman's", "reginald ipa"], brewery: "Blackman's Brewery", style: "IPA", abv: 6.2 },
  { key: "blackmans_mervyn_pale_ale", name: "Blackman's Mervyn Pale Ale", aliases: ["mervyn", "blackmans pale"], brewery: "Blackman's Brewery", style: "Pale ale", abv: 4.6 },
  { key: "quiet_deeds_juicy_ipa", name: "Quiet Deeds Juicy IPA", aliases: ["quiet deeds", "quiet deeds juicy"], brewery: "Deeds Brewing", style: "Juicy IPA", abv: 6.5 },
  { key: "jetty_road_pale_ale", name: "Jetty Road Pale Ale", aliases: ["jetty road", "jetty road pale"], brewery: "Jetty Road", style: "Pale ale", abv: 4.8 },
  { key: "bad_shepherd_victoria_pale_ale", name: "Bad Shepherd Victoria Pale Ale", aliases: ["bad shepherd", "victoria pale ale"], brewery: "Bad Shepherd", style: "Pale ale", abv: 4.2 },
  { key: "brick_lane_one_love_pale", name: "Brick Lane One Love Pale Ale", aliases: ["brick lane", "one love", "one love pale"], brewery: "Brick Lane", style: "Pale ale", abv: 4.4 },
  { key: "brick_lane_sidewinder", name: "Brick Lane Sidewinder Hazy Pale", aliases: ["sidewinder", "brick lane hazy"], brewery: "Brick Lane", style: "Hazy pale ale", abv: 4.0 },
  { key: "kaiju_krush", name: "Kaiju Krush", aliases: ["kaiju", "kaiju krush"], brewery: "Kaiju Beer", style: "Tropical pale ale", abv: 4.7 },
  { key: "kaiju_aftermath", name: "Kaiju Aftermath", aliases: ["kaiju aftermath"], brewery: "Kaiju Beer", style: "Double IPA", abv: 9.1 },
  { key: "temple_anytime_ipa", name: "Temple Anytime IPA", aliases: ["temple", "anytime ipa", "temple anytime"], brewery: "Temple Brewing", style: "IPA", abv: 4.7 },
  { key: "bridge_road_beechworth_pale", name: "Bridge Road Beechworth Pale Ale", aliases: ["bridge road", "beechworth pale"], brewery: "Bridge Road Brewers", style: "Pale ale", abv: 4.8 },
  { key: "bridge_road_bling_ipa", name: "Bridge Road Bling IPA", aliases: ["bling ipa", "bridge road ipa"], brewery: "Bridge Road Brewers", style: "IPA", abv: 5.8 },
  { key: "colonial_south_west_sour", name: "CBCo South West Sour", aliases: ["cbco sour", "colonial sour", "south west sour"], brewery: "CBCo Brewing", style: "Sour", abv: 4.6 },
  { key: "colonial_pale_ale", name: "CBCo Pale Ale", aliases: ["cbco pale", "colonial pale"], brewery: "CBCo Brewing", style: "Pale ale", abv: 4.4 },
  { key: "matilda_bay_redback", name: "Matilda Bay Redback", aliases: ["redback", "matilda bay redback"], brewery: "Matilda Bay", style: "Wheat beer", abv: 4.7 },
  { key: "asahi_super_dry", name: "Asahi Super Dry", aliases: ["asahi", "asahi super dry"], brewery: "Asahi", style: "Lager", abv: 5.0 },
  { key: "sapporo_premium", name: "Sapporo Premium", aliases: ["sapporo", "sapporo premium"], brewery: "Sapporo", style: "Lager", abv: 4.9 },
  { key: "kirin_ichiban", name: "Kirin Ichiban", aliases: ["kirin", "kirin ichiban"], brewery: "Kirin", style: "Lager", abv: 5.0 },
  { key: "corona_extra", name: "Corona Extra", aliases: ["corona", "corona extra"], brewery: "Corona", style: "Lager", abv: 4.5 },
  { key: "heineken", name: "Heineken", aliases: ["heineken"], brewery: "Heineken", style: "Lager", abv: 5.0 },
  { key: "peroni_nastro_azzurro", name: "Peroni Nastro Azzurro", aliases: ["peroni", "peroni nastro"], brewery: "Peroni", style: "Lager", abv: 5.0 },
  { key: "birra_moretti", name: "Birra Moretti", aliases: ["moretti", "birra moretti"], brewery: "Birra Moretti", style: "Lager", abv: 4.6 },
  { key: "stella_artois", name: "Stella Artois", aliases: ["stella", "stella artois"], brewery: "Stella Artois", style: "Lager", abv: 4.8 },
  { key: "carlsberg", name: "Carlsberg", aliases: ["carlsberg"], brewery: "Carlsberg", style: "Lager", abv: 5.0 },
  { key: "pilsner_urquell", name: "Pilsner Urquell", aliases: ["pilsner urquell", "urquell"], brewery: "Pilsner Urquell", style: "Pilsner", abv: 4.4 },
  { key: "brooklyn_lager", name: "Brooklyn Lager", aliases: ["brooklyn", "brooklyn lager"], brewery: "Brooklyn Brewery", style: "Lager", abv: 5.2 },
  { key: "brooklyn_defender_ipa", name: "Brooklyn Defender IPA", aliases: ["defender ipa", "brooklyn ipa"], brewery: "Brooklyn Brewery", style: "IPA", abv: 5.5 },
  { key: "blue_moon_belgian_white", name: "Blue Moon Belgian White", aliases: ["blue moon", "blue moon belgian white"], brewery: "Blue Moon", style: "Witbier", abv: 5.4 },
  { key: "hoegaarden", name: "Hoegaarden", aliases: ["hoegaarden"], brewery: "Hoegaarden", style: "Witbier", abv: 4.9 },
  { key: "erdinger_weissbier", name: "Erdinger Weissbier", aliases: ["erdinger", "erdinger weissbier"], brewery: "Erdinger", style: "Wheat beer", abv: 5.3 },
  { key: "weihenstephaner_hefeweissbier", name: "Weihenstephaner Hefeweissbier", aliases: ["weihenstephaner", "weihenstephan"], brewery: "Weihenstephaner", style: "Wheat beer", abv: 5.4 },
  { key: "paulaner_munchner_lager", name: "Paulaner Münchner Lager", aliases: ["paulaner", "paulaner lager", "paulaner munchner"], brewery: "Paulaner", style: "Lager", abv: 4.9 },
  { key: "kilkenny", name: "Kilkenny", aliases: ["kilkenny"], brewery: "Kilkenny", style: "Irish cream ale", abv: 4.3 },
  { key: "brookvale_union_ginger_beer", name: "Brookvale Union Ginger Beer", aliases: ["brookvale", "brookvale ginger beer", "ginger beer"], brewery: "Brookvale Union", style: "Alcoholic ginger beer", abv: 4.0 },
  { key: "somersby_apple_cider", name: "Somersby Apple Cider", aliases: ["somersby", "somersby apple"], brewery: "Somersby", style: "Cider", abv: 4.5 },
  { key: "bulmers_original_cider", name: "Bulmers Original Cider", aliases: ["bulmers", "bulmers original"], brewery: "Bulmers", style: "Cider", abv: 4.7 },
  { key: "strongbow_original_cider", name: "Strongbow Original Cider", aliases: ["strongbow", "strongbow original"], brewery: "Strongbow", style: "Cider", abv: 5.0 },
  { key: "mercury_draught_cider", name: "Mercury Draught Cider", aliases: ["mercury", "mercury cider"], brewery: "Mercury", style: "Cider", abv: 5.2 },
  { key: "willie_smiths_organic_cider", name: "Willie Smith's Organic Cider", aliases: ["willie smiths", "willie smith's", "willie smiths cider"], brewery: "Willie Smith's", style: "Cider", abv: 5.4 },
];
