-- Intentionally empty.
--
-- This migration version is retained so projects that recorded it do not lose
-- migration-history alignment. The off-site destination belongs to a separate
-- Supabase project and its setup SQL lives outside the production application
-- migration chain at ops/supabase/independent-backup-project-storage.sql.
